version: "3.7"
services:
  authservice_db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
    volumes:
      - ./docker-volumes/postgres/:/var/lib/postgresql/data
    ports:
      - "${DB_CONTAINER_PORT}:5432"
    deploy:
      replicas: 1