"""init

Revision ID: bc81c684458b
Revises: 
Create Date: 2022-10-23 16:09:09.271563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bc81c684458b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            comment="Идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "login", sa.String(length=255), nullable=True, comment="Логин"
        ),
        sa.Column(
            "full_name", sa.String(length=255), nullable=True, comment="ФИО"
        ),
        sa.Column(
            "role", sa.String(length=255), nullable=True, comment="Роль"
        ),
        sa.Column(
            "password", sa.String(length=255), nullable=True, comment="Пароль"
        ),
        sa.Column(
            "last_login",
            sa.DateTime(),
            nullable=True,
            comment="Последний вход",
        ),
        sa.Column(
            "is_blocked", sa.Boolean(), nullable=True, comment="Заблокирован?"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            comment="Идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "token",
            sa.String(length=1000),
            nullable=True,
            comment="Токен доступа",
        ),
        sa.Column(
            "expired_at",
            sa.DateTime(),
            nullable=True,
            comment="Длительность жизни токена",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("users")
    # ### end Alembic commands ###
