"""_user_upd

Revision ID: c9ae720d5a53
Revises: bc81c684458b
Create Date: 2022-10-27 06:06:53.942527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9ae720d5a53"
down_revision = "bc81c684458b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_blocked")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_blocked",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
            comment="Заблокирован?",
        ),
    )
    # ### end Alembic commands ###
